Re-enable cuspatial tests and dependency.
rapidsai/cuspatial pull request #1253
Opened 2023-08-07 17:13 UTC by thomcom

## Description
A poorly understood cuproj->cuspatial dependency required that cuspatial be removed from cuproj's tests during the 23.08->23.10 merge rebase. This PR re-enables those tests.

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cuspatial/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2023-08-10 04:31 UTC, isVoid commented
I was a bit out of loop of this in 23.08, in which PR did you disabled the cuproj tests in 23.08?

2023-08-10 14:26 UTC, thomcom commented
They weren't disabled in 23.08, they were disabled in the 23.08 -> 23.10 merge commit because of the dependency that cuproj has on cuspatial, which caused ci to load the cuspatial-nightly build instead of the in-PR build of cuspatial, running cuproj 23.10 tests against cuspatial 23.08.

2023-08-14 22:16 UTC, harrism commented on dependencies.yaml
> +          - cuspatial=23.10.*
```suggestion
          - cuspatial==23.10.*
```

And re-run pre-commit.

2023-09-25 21:28 UTC, harrism commented
/ok to test

2023-09-28 03:14 UTC, harrism commented
@thomcom your .devcontainer folder doesn't match the latest for 23.10, which has separate folders: 

```
.devcontainer/
├── cuda11.8-conda
│   └── devcontainer.json
├── cuda11.8-pip
│   └── devcontainer.json
├── cuda12.0-conda
│   └── devcontainer.json
├── cuda12.0-pip
│   └── devcontainer.json
├── Dockerfile
└── README.md
```

2023-09-28 06:01 UTC, harrism commented
Please remember:

/ok to test

2023-09-28 06:01 UTC, harrism commented
/ok to test

2023-09-28 20:14 UTC, thomcom commented
/ok to test

2023-10-04 01:34 UTC, harrism commented
/ok to test

2023-10-04 01:39 UTC, harrism requested changes
One dependency request. Remember to run `pre-commit run` before committing when you make this change.

2023-10-04 01:39 UTC, harrism commented on dependencies.yaml
>            - pyproj
```suggestion
          - pyproj>=3.6.0,<3.7a0
```

Apparently not specifying a loose pin causes conda to implicitly use a tight pin to the latest version. Doing this should avoid the problem of pinning to an older libtiff that proj 9.2 uses, and caused solver problems for us. Am I right @raydouglass ? See https://github.com/rapidsai/cuspatial/pull/1276

2023-10-04 20:36 UTC, harrism commented
/ok to test

2023-10-04 23:21 UTC, harrism commented
/ok to test

2023-10-04 23:21 UTC, harrism approved these changes

2023-10-05 00:42 UTC, bdice commented on conda/environments/all_cuda-120_arch-x86_64.yaml
> +- cuspatial==23.10.*
This is coming from `dependencies.yaml`. We don't want cuspatial as a requirement of its own development environment.

2023-10-05 01:43 UTC, harrism commented
/ok to test

2023-10-05 02:42 UTC, harrism commented
/ok to test

2023-10-05 20:43 UTC, bdice approved these changes

2023-10-05 20:43 UTC, bdice commented
/merge

2023-10-05 21:03 UTC, ajschmidt8 approved these changes

2023-10-05 21:03 UTC, merged

2023-10-05 21:03 UTC, raydouglass approved these changes