Remove proj and sqlite from libcuspatial recipe.
rapidsai/cuspatial pull request #1308
Opened 2023-12-06 23:29 UTC by bdice

## Description
This cleans up some packaging. We no longer need `proj` or `sqlite` in libcuspatial.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cuspatial/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2023-12-08 01:48 UTC, vyasr requested changes
Please also remove from dependencies.yaml: https://github.com/rapidsai/cuspatial/blob/branch-24.02/dependencies.yaml#L128 (there's a separate dependency list for cuproj https://github.com/rapidsai/cuspatial/blob/branch-24.02/dependencies.yaml#L160).

2023-12-08 01:58 UTC, vyasr commented
Also while doing that, we should consider pinning proj in dependencies.yaml (unless the migration is completed on cf prior to this PR merging, in which case we can remove the pinnings in this PR).

2023-12-09 21:01 UTC, harrism commented
My concern with removing the `add_subdirectory(cuproj)` line is that libcuproj will not be built. THe source structure is:

```
cpp
 | - CMakeLists.txt (builds libcuspatial, includes proj)
 |--> cuproj
           | - CMakeLists.txt
 ```

This is a bit confusing if the build process is separate. Perhaps we should change it to:

```
 |--> cuspatial
         | - CMakeLists.txt
 |--> proj
           | - CMakeLists.txt
```

But that's a pretty big change. Thoughts?

2023-12-09 21:41 UTC, bdice commented
@harrism I agree that there are varying degrees of scope that this could take. Let's limit the scope in this PR and restructure parts of `dependencies.yaml` but leave the rest of the refactor for another PR.

I think what I would propose for the second PR is:
- Organize the C++ code to something like
```
cpp
 |--> cuspatial
         | - CMakeLists.txt
 |--> cuproj
         | - CMakeLists.txt
```
- Consider adding a separate `libcuproj` package (with changes to `build.sh`, `ci/build_cpp.sh`, `ci/build_python.sh`, a new conda recipe, etc.)

libcuproj is header-only, so the conda package contents would be just headers (and it would define the build dependencies for those headers), like for rmm. It's also fine for us to just _not_ have a `libcuproj` package and instead build the C++ code in the `cuproj` Python build steps. I would still advocate for the C++ file organization above, either way.

2023-12-10 11:21 UTC, harrism approved these changes

2023-12-12 02:28 UTC, vyasr commented
I don't think this PR is going to work until the packages are restructured as discussed in the above threads. Right now cuproj is build as part of cuspatial, so the cuproj requirements are needed for the cuspatial build. You may have to do the package restructuring in order to simplify dependencies the way that you want.

2023-12-13 19:41 UTC, ajschmidt8 approved these changes

2024-08-05 15:02 UTC, bdice commented
Closing as stale. I do not plan to refactor the packages as described above in the near term.

2024-08-05 15:02 UTC, closed without merging