[REVIEW] Initiate cuspatial java layer binding [skip ci]
rapidsai/cuspatial pull request #290
Opened 2020-09-10 05:49 UTC by byin001

2020-09-10 05:49 UTC, GPUtester commented
Can one of the admins verify this patch?

2020-09-10 05:49 UTC, GPUtester commented
Can one of the admins verify this patch?

2020-09-15 03:46 UTC, harrism commented
OK to test

2020-09-15 03:48 UTC, harrism commented on CHANGELOG.md
> +- PR #290 Add Java binding hence a cuSpatial JAR package for Java users.
```suggestion
- PR #290 Add Java bindings and a cuSpatial JAR package for Java users.
```

2020-09-30 15:02 UTC, revans2 requested changes
Overall it looks good.  Mostly I just saw a few nits.

Please note that I am just looking generally at the java and JNI code.  It is almost all boilerplate so I feel fairly confident in this review, but I would not be able to detect some types issues without more of an understanding of the cuspacial APIs themselves.

2020-10-10 11:39 UTC, byin001 commented on java/pom.xml
> +    <version>0.15-SNAPSHOT</version>
updated to 0.16-SNAPSHOT

2020-10-10 11:40 UTC, byin001 commented on java/pom.xml
> +                            //def librp = ~/librmm\\.so\\s+=>\\s+(.*)librmm.*\\.so\\s+.*/
removed

2020-10-10 11:40 UTC, byin001 commented on java/src/main/java/ai/rapids/cuspatial/CuSpatial.java
> +  public static ColumnVector pointInPolygon(ColumnVector testPointsX, ColumnVector testPointsY,
javadoc completed

2020-10-10 11:41 UTC, byin001 commented on java/src/main/java/ai/rapids/cuspatial/CuSpatialException.java
> + * Copyright (c) 2019, NVIDIA CORPORATION.
typo corrected to 2020

2020-10-10 11:41 UTC, byin001 commented on java/src/main/native/src/cuSpatialJni.cpp
> +jlongArray convert_table_for_return(JNIEnv *env, std::unique_ptr<cudf::table> &table_result) {
anonymous namespace added

2020-10-10 11:41 UTC, byin001 commented on java/src/main/native/src/cuSpatialJni.cpp
> +jlongArray convert_columns_for_return(JNIEnv *env, std::vector<std::unique_ptr<cudf::column>> &columns) {
anonymous namespace added

2020-10-12 13:05 UTC, revans2 approved these changes
Looks great

2020-10-12 22:46 UTC, harrism requested changes
A few doc edits.

2020-10-13 01:53 UTC, harrism approved these changes

2020-10-13 01:53 UTC, merged