[REVIEW] Updating CMakeLists.txt to add aarch64 support
rapidsai/cuspatial pull request #293
Opened 2020-09-15 20:33 UTC by JasonAtNvidia

Changing GPU_ARCHS portion of CMakeLists.txt to add flag to detect aarch64 architectures and chose GenCode flags based on those.

2020-09-15 20:33 UTC, GPUtester commented
Can one of the admins verify this patch?

2020-09-15 20:33 UTC, GPUtester commented
Can one of the admins verify this patch?

2020-09-15 21:56 UTC, kkraus14 approved these changes

2020-09-15 21:56 UTC, kkraus14 commented
ok to test

2020-09-15 21:56 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-09-16 00:37 UTC, harrism requested changes

2020-09-16 00:37 UTC, harrism commented on cpp/CMakeLists.txt
> +    if((CUDA_VERSION_MAJOR EQUAL 11) OR (CUDA_VERSION_MAJOR GREATER 11))
These should all be simplified using `GREATER_EQUAL`
```suggestion
    if(CUDA_VERSION_MAJOR GREATER_EQUAL 9)
      set(GPU_ARCHS "${GPU_ARCHS};72")
    endif()
    if(CUDA_VERSION_MAJOR GREATER_EQUAL 11)
```

2020-09-16 00:37 UTC, harrism commented on cpp/CMakeLists.txt
> +    if((CUDA_VERSION_MAJOR EQUAL 9) OR (CUDA_VERSION_MAJOR GREATER 9))
GREATER_EQUAL on all of these too.

2021-03-12 14:33 UTC, trxcllnt commented
I believe this is handled in https://github.com/rapidsai/cuspatial/pull/365/

2021-03-12 15:11 UTC, JasonAtNvidia commented
> I believe this is handled in #365

It does appear that the new upgrades to CMakeLists in #365 includes all of the features I added to other CMakeLists to add aarch64 support for Jetson.  I am going to close this bug based on that.

2021-03-12 15:11 UTC, closed without merging