[WIP] Upgrade to libcu++ on GitHub
rapidsai/cuspatial pull request #297
Opened 2020-09-23 16:53 UTC by trxcllnt

Work-in-progress branch to update to libcu++ on Github.

* Related cuDF PR: https://github.com/rapidsai/cudf/pull/6275
* Related libcu++ PR: https://github.com/NVIDIA/libcudacxx/pull/10
* Depends on/merges in changes from https://github.com/rapidsai/cuspatial/pull/292

2020-09-23 16:53 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-12-08 03:08 UTC, harrism requested changes
Just some header stuff.

2020-12-08 03:08 UTC, harrism commented on cpp/include/cuspatial/cubic_spline.hpp
> +#include "cudf/types.hpp"
clangd is messing with you.

```suggestion
```

2020-12-08 03:08 UTC, harrism commented on cpp/src/indexing/construction/detail/utilities.cuh
> +#include "rmm/cuda_stream_view.hpp"
```suggestion
```

2020-12-08 03:08 UTC, harrism commented on cpp/src/join/detail/traversal.cuh
>  #include "utility/z_order.cuh"
```suggestion
#include <utility/z_order.cuh>
```

2020-12-08 03:08 UTC, harrism commented on cpp/src/spatial/hausdorff.cu
> +#include "utility/size_from_offsets.cuh"
```suggestion
#include <utility/scatter_output_iterator.cuh>
#include <utility/size_from_offsets.cuh>
```

2020-12-08 16:01 UTC, trxcllnt commented
@harrism looks like the base was set to branch-0.16 for some reason. Changing it invalidated some of your suggestions, but I'll merge the rest.

2020-12-08 20:28 UTC, trxcllnt commented
rerun tests

2020-12-09 01:16 UTC, trxcllnt commented
rerun tests

2020-12-09 01:20 UTC, harrism approved these changes

2020-12-09 01:28 UTC, cwharris approved these changes

2020-12-09 02:22 UTC, merged