[WIP] Update conda dev yml files
rapidsai/cuspatial pull request #303
Opened 2020-10-07 22:45 UTC by Salonijain27

removed files used to build a conda dev environment for CUDA 9.2 and CUDA 10.0 
added a file for CUDA 11.0
added cmake and cython libraries into the yml files
updated cudf to 0.16.* from 0.15

2020-10-07 22:46 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-10-08 02:57 UTC, harrism approved these changes
Looks good. Thanks @Salonijain27 !

2020-10-08 14:39 UTC, ajschmidt8 approved these changes

2020-10-09 05:11 UTC, harrism requested changes

2020-10-09 05:11 UTC, harrism commented on conda/environments/cuspatial_dev_cuda10.1.yml
> +  - cmake_setuptools>=0.1.3
@kkraus14 says we don't need this.
```suggestion
```

2020-10-09 05:11 UTC, harrism commented on conda/environments/cuspatial_dev_cuda10.2.yml
> +  - cmake_setuptools>=0.1.3
```suggestion
```

2020-10-09 05:11 UTC, harrism commented on conda/environments/cuspatial_dev_cuda11.0.yml
> +  - cmake_setuptools>=0.1.3
```suggestion
```

2020-10-09 17:57 UTC, kkraus14 approved these changes

2020-10-12 04:42 UTC, harrism commented
rerun tests

2020-10-12 13:57 UTC, kkraus14 approved these changes

2020-10-12 13:58 UTC, merged