add support for space in workspace
rapidsai/cuspatial pull request #385
Opened 2021-04-15 19:44 UTC by jolorunyomi

# Summary
Add support for space in workspace

2021-04-15 20:08 UTC, ajschmidt8 approved these changes
just a few stylistic suggestions here to move some terminating quotes to the end of the line, but should be fine either way.

2021-04-15 20:08 UTC, ajschmidt8 commented on ci/docs/build.sh
> +mv "$PROJECT_WORKSPACE/docs/build/html/"* "$DOCS_WORKSPACE/api/cuspatial/"$BRANCH_VERSION
```suggestion
mv "$PROJECT_WORKSPACE/docs/build/html/"* "$DOCS_WORKSPACE/api/cuspatial/$BRANCH_VERSION"
```

I don't think there's any harm in moving this to the end of the line

2021-04-15 20:08 UTC, ajschmidt8 commented on ci/docs/build.sh
> +    rm -rf "$DOCS_WORKSPACE/api/"$PROJECT/$BRANCH_VERSION/*
```suggestion
    rm -rf "$DOCS_WORKSPACE/api/$PROJECT/$BRANCH_VERSION/"*
```

2021-05-18 12:33 UTC, trxcllnt commented
rerun tests

2021-05-18 12:37 UTC, trxcllnt requested changes

2021-05-18 12:37 UTC, trxcllnt commented on ci/gpu/build.sh
> +    export LD_LIBRARY_PATH="$WORKSPACE/ci/artifacts/cuspatial/cpu/conda_work/cpp/build":$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
```suggestion
    export LD_LIBRARY_PATH="$WORKSPACE/ci/artifacts/cuspatial/cpu/conda_work/cpp/build:$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
```

2021-05-18 13:39 UTC, trxcllnt commented on ci/local/build.sh
> +cd "\$WORKSPACE"
```suggestion
cd \"\$WORKSPACE\"
```

2021-05-25 02:28 UTC, harrism commented
@jolorunyomi can you respond to @trxcllnt 's review? Thanks.

2021-05-25 23:57 UTC, trxcllnt commented
rerun tests

2021-05-27 00:16 UTC, harrism commented
rerun tests

2021-05-28 19:24 UTC, ajschmidt8 commented on ci/cpu/build.sh
> +        -c "$WORKSPACE/ci/artifacts/cuspatial/cpu/conda-bld/" conda/recipes/cuspatial
```suggestion
        -c "$WORKSPACE/ci/artifacts/cuspatial/cpu/.conda-bld/" conda/recipes/cuspatial
```

looks like a `.` was mistakenly removed here.

2021-06-01 16:17 UTC, ajschmidt8 commented
should be good to merge this pending @trxcllnt's re-review

2021-06-08 20:50 UTC, trxcllnt approved these changes

2021-06-09 11:34 UTC, harrism commented
@gpucibot merge

2021-06-09 11:34 UTC, merged