[WIP] Pin gdal to 3.3.x
rapidsai/cuspatial pull request #420
Opened 2021-06-15 10:39 UTC by weiji14

Bump `gdal` from 3.2.x to 3.3.x. Supersedes #347. This is inline with conda-forge's current migration to gdal=3.3.x (see https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1506 and https://conda-forge.org/status/#gdal33).

Update on rapidsai/integration will come shortly.

2021-06-15 10:39 UTC, GPUtester commented
Can one of the admins verify this patch?

2021-06-15 10:39 UTC, GPUtester commented
Can one of the admins verify this patch?

2021-06-18 20:02 UTC, ajschmidt8 commented
ok to test

2021-06-22 03:40 UTC, weiji14 commented
There are 2 failing tests. Not quite sure what to do with these though :sweat_smile:

```bash
[  FAILED  ] PIPRefineTestLarge/0.TestLarge, where TypeParam = float (1063 ms)
[----------] 1 test from PIPRefineTestLarge/0 (1063 ms total)

[----------] 1 test from PIPRefineTestLarge/1, where TypeParam = double
[ RUN      ] PIPRefineTestLarge/1.TestLarge
../tests/utilities/column_utilities.cu:68: Failure
Expected equality of these values:
  lhs.size()
    Which is: 0
  rhs.size()
    Which is: 885
../tests/utilities/column_utilities.cu:68: Failure
Expected equality of these values:
  lhs.size()
    Which is: 0
  rhs.size()
    Which is: 885
../tests/utilities/column_utilities.cu:68: Failure
Expected equality of these values:
  lhs.size()
    Which is: 0
  rhs.size()
    Which is: 885
[  FAILED  ] PIPRefineTestLarge/1.TestLarge, where TypeParam = double (30 ms)
[----------] 1 test from PIPRefineTestLarge/1 (30 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 2 test suites ran. (1093 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] PIPRefineTestLarge/0.TestLarge, where TypeParam = float
[  FAILED  ] PIPRefineTestLarge/1.TestLarge, where TypeParam = double

 2 FAILED TESTS
```

2021-06-22 19:08 UTC, ajschmidt8 commented
> There are 2 failing tests. Not quite sure what to do with these though 

@thomcom, any thoughts here?

2021-07-06 18:54 UTC, thomcom commented
For some reason I missed this in my github notifications feed, I'll take a look at it this week. Thanks!

2021-07-20 21:41 UTC, harrism commented
@thomcom any update? Moving to 21.10, please retarget the branch.

2021-08-18 21:24 UTC, thomcom commented
rerun tests

2021-08-19 02:48 UTC, weiji14 reviewed
Did the tests pass? And can we move on with https://github.com/rapidsai/integration/pull/300?

2021-08-19 02:48 UTC, weiji14 commented on ci/gpu/build.sh
> +# gpuci_mamba_retry install "gdal=3.3.1"
```suggestion
# gpuci_mamba_retry install "your-pkg=1.0.0"
```

2021-08-19 15:20 UTC, Ethyling commented
rerun tests

2021-08-19 16:34 UTC, cwharris approved these changes

2021-08-19 16:34 UTC, cwharris requested changes
errr, didn't realize this was wip.

2021-08-19 21:26 UTC, thomcom commented
rerun tests

2021-08-19 22:37 UTC, Ethyling commented
rerun tests

2021-08-19 23:51 UTC, thomcom commented
@cwharris any chance you can reformat this pr with `scripts/run-clang-format.py` assuming you already have clang-format 11? Mine is 8.0.1 in conda and I'm not confident of how to get to 11.0.0 quickly.

2021-08-20 17:37 UTC, thomcom commented
@gpucibot merge

2021-08-20 17:47 UTC, cwharris approved these changes

2021-08-20 17:52 UTC, thomcom approved these changes

2021-08-20 17:52 UTC, thomcom commented
@gpucibot merge

2021-08-20 17:53 UTC, thomcom commented
@dillon-cullinan can I get an approve 420?

2021-08-20 17:53 UTC, ajschmidt8 approved these changes

2021-08-20 17:59 UTC, thomcom commented
@gpucibot merge

2021-08-20 17:59 UTC, merged