[FIX] Fix compile error in distance benchmark
rapidsai/cuspatial pull request #596
Opened 2022-07-19 14:22 UTC by trxcllnt

This PR fixes the following compile error:
```
pairwise_linestring_distance.cu (80): error: too many initializer values
          detected during:
            instantiation of "std::tuple<rmm::device_vector<cuspatial::cartesian_2d<T>>, rmm::device_vector<int32_t>> generate_linestring(int32_t, int32_t, T, cuspatial::cartesian_2d<T>) [with T=float]" 
```

2022-07-19 22:42 UTC, harrism commented
Did this not get caught by CI because we are not building benchmarks by default in CI? I was going to look at that today, coincidentally.

The old version of the code looks correct to me -- where did this fail? It doesn't fail locally for me or @isVoid .

2022-07-21 22:20 UTC, vyasr commented
Given that all benchmarks compiled successfully in #597 this change is also suspicious. Is this perhaps a compiler bug on a new system (Hopper)?

2022-07-22 16:19 UTC, thomcom approved these changes

2022-07-25 19:54 UTC, trxcllnt commented
Here's the full error:
```shell
FAILED: benchmarks/CMakeFiles/DISTANCES_BENCH.dir/pairwise_linestring_distance.cu.o 
/usr/local/bin/nvcc -forward-unknown-to-host-compiler -DCUDF_VERSION=22.08.00 -DGTEST_LINKED_AS_SHARED_LIBRARY=1 -DJITIFY_USE_CACHE -DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_INFO -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP -I/home/ptaylor/dev/rapids/cuspatial/cpp/benchmarks -I/home/ptaylor/dev/rapids/cuspatial/cpp -I/home/ptaylor/dev/rapids/cuspatial/cpp/src -I/home/ptaylor/dev/rapids/cuspatial/cpp/build/cuda-11.6.2/fea-drop-glue-code/release/_deps/benchmark-src/src/../include -I/home/ptaylor/dev/rapids/cudf/cpp/build/cuda-11.6.2/branch-22.08/release/_deps/libcudacxx-src/include -I/home/ptaylor/dev/rapids/cudf/cpp/build/cuda-11.6.2/branch-22.08/release/_deps/thrust-src -I/home/ptaylor/dev/rapids/cudf/cpp/build/cuda-11.6.2/branch-22.08/release/_deps/thrust-src/dependencies/cub -I/home/ptaylor/dev/rapids/cuspatial/cpp/include -I/home/ptaylor/dev/rapids/cuspatial/cpp/build/cuda-11.6.2/fea-drop-glue-code/release/_deps/nvbench-src -I/home/ptaylor/dev/rapids/cuspatial/cpp/build/cuda-11.6.2/fea-drop-glue-code/release/_deps/nvbench-build -isystem=/home/ptaylor/dev/rapids/cudf/cpp -isystem=/home/ptaylor/dev/rapids/cudf/cpp/src -isystem=/home/ptaylor/dev/rapids/compose/etc/conda/cuda_11.6/envs/rapids/include -isystem=/home/ptaylor/dev/rapids/cudf/cpp/build/cuda-11.6.2/branch-22.08/release/_deps/dlpack-src/include -isystem=/home/ptaylor/dev/rapids/cudf/cpp/build/cuda-11.6.2/branch-22.08/release/_deps/jitify-src -isystem=/home/ptaylor/dev/rapids/cudf/cpp/include -isystem=/home/ptaylor/dev/rapids/cudf/cpp/build/cuda-11.6.2/branch-22.08/release/include -isystem=/home/ptaylor/dev/rapids/rmm/include -isystem=/usr/local/cuda/include -Xcompiler=-fdiagnostics-color=always -Xcompiler=-Wno-deprecated-declarations -O3 -DNDEBUG --generate-code=arch=compute_75,code=[sm_75] -Xcompiler=-fPIE -Xcompiler=-Wno-parentheses --expt-extended-lambda --expt-relaxed-constexpr -Werror=all-warnings -Xcompiler=-Wall,-Werror,-Wno-error=deprecated-declarations -Xfatbin=-compress-all -Xcompiler=-Wno-deprecated-declarations -Werror=cross-execution-space-call -Xcompiler -pthread -std=c++17 -MD -MT benchmarks/CMakeFiles/DISTANCES_BENCH.dir/pairwise_linestring_distance.cu.o -MF benchmarks/CMakeFiles/DISTANCES_BENCH.dir/pairwise_linestring_distance.cu.o.d -x cu -c /home/ptaylor/dev/rapids/cuspatial/cpp/benchmarks/pairwise_linestring_distance.cu -o benchmarks/CMakeFiles/DISTANCES_BENCH.dir/pairwise_linestring_distance.cu.o
/home/ptaylor/dev/rapids/cuspatial/cpp/benchmarks/pairwise_linestring_distance.cu(80): error: too many initializer values
          detected during:
            instantiation of "std::tuple<rmm::device_vector<cuspatial::cartesian_2d<T>>, rmm::device_vector<int32_t>> generate_linestring(int32_t, int32_t, T, cuspatial::cartesian_2d<T>) [with T=float]" 
(100): here
            instantiation of "void pairwise_linestring_distance_benchmark(nvbench::state &, nvbench::type_list<T>) [with T=float]" 
(140): here
            instantiation of "void pairwise_linestring_distance_benchmark_line_140::operator()(nvbench::state &, nvbench::type_list<Ts...>) [with Ts=<float>]" 
_deps/nvbench-src/nvbench/detail/type_list_impl.cuh(100): here
            instantiation of "void nvbench::tl::detail::foreach<TypeList,Functor,Is...>(std::index_sequence<Is...>, Functor &&) [with TypeList=nvbench::type_list<nvbench::type_list<float>, nvbench::type_list<double>>, Functor=lambda [](auto)->auto, Is=<0UL, 1UL>]" 
_deps/nvbench-src/nvbench/detail/type_list_impl.cuh(109): here
            instantiation of "void nvbench::tl::detail::foreach<TypeList,Functor>(Functor &&) [with TypeList=nvbench::type_list<nvbench::type_list<float>, nvbench::type_list<double>>, Functor=lambda [](auto)->auto]" 
_deps/nvbench-src/nvbench/type_list.cuh(140): here
            [ 3 instantiation contexts not shown ]
            instantiation of "void nvbench::benchmark<KernelGenerator, TypeAxes>::do_run() [with KernelGenerator=pairwise_linestring_distance_benchmark_line_140, TypeAxes=nvbench::type_list<floating_point_types>]" 
_deps/nvbench-src/nvbench/benchmark.cuh(65): here
            implicit generation of "nvbench::benchmark<KernelGenerator, TypeAxes>::~benchmark() noexcept [with KernelGenerator=pairwise_linestring_distance_benchmark_line_140, TypeAxes=nvbench::type_list<floating_point_types>]" 
_deps/nvbench-src/nvbench/benchmark.cuh(65): here
            instantiation of class "nvbench::benchmark<KernelGenerator, TypeAxes> [with KernelGenerator=pairwise_linestring_distance_benchmark_line_140, TypeAxes=nvbench::type_list<floating_point_types>]" 
_deps/nvbench-src/nvbench/benchmark.cuh(65): here
            instantiation of "nvbench::benchmark<KernelGenerator, TypeAxes>::benchmark() [with KernelGenerator=pairwise_linestring_distance_benchmark_line_140, TypeAxes=nvbench::type_list<floating_point_types>]" 
/home/ptaylor/dev/rapids/compose/etc/conda/cuda_11.6/envs/rapids/x86_64-conda-linux-gnu/include/c++/9.4.0/bits/unique_ptr.h(857): here
            instantiation of "std::_MakeUniq<_Tp>::__single_object std::make_unique<_Tp,_Args...>(_Args &&...) [with _Tp=nvbench::benchmark<pairwise_linestring_distance_benchmark_line_140, nvbench::type_list<floating_point_types>>, _Args=<>]" 
(140): here

1 error detected in the compilation of "/home/ptaylor/dev/rapids/cuspatial/cpp/benchmarks/pairwise_linestring_distance.cu".

```

2022-07-25 22:01 UTC, harrism commented
Hmmm, I think the original code should work -- it's initializing the two elements using an implicitly generated constructor. Your change forces it to use a different implicitly generated constructor (initializer list constructor?)

2022-08-03 21:37 UTC, thomcom commented
I had the same error, @trxcllnt just now building cuspatial from `branch-22.10`. Your fix however doesn't work for me, but `({})` does.

2022-08-03 21:38 UTC, thomcom requested changes

2022-08-03 21:38 UTC, thomcom commented on cpp/benchmarks/pairwise_linestring_distance.cu
> +    return cartesian_2d<T>{{prev.x + segment_length * rad.x, prev.y + segment_length * rad.y}};
```suggestion
    return cartesian_2d<T>({prev.x + segment_length * rad.x, prev.y + segment_length * rad.y});
```

2022-08-03 21:38 UTC, thomcom commented on cpp/benchmarks/pairwise_linestring_distance.cu
> +    return cartesian_2d<T>{{prev.x + segment_length * rad.x, prev.y + segment_length * rad.y}};
It's mysterious that we have three different builds taking place, one that works, one that works with your fix, and one that works with mine.

2022-08-04 13:04 UTC, jrhemstad commented
The alternative is to add a constructor to `vec_2d` and import it in `cartesian_2d`

https://godbolt.org/z/Gh6v1zWKa

2022-08-04 17:55 UTC, trxcllnt commented
@jrhemstad good catch, I'll update this PR

2022-08-04 20:09 UTC, trxcllnt commented
@jrhemstad that didn't work for me, but I pushed a new fix that does seem to be working.

2022-08-04 22:20 UTC, harrism reviewed
What we really want is just `return prev + segment_length * rad;`  what if you change the `auto const&` parameters to explicit `cartesian_2d<T>`.

2022-08-10 19:29 UTC, trxcllnt commented
@gpucibot merge

2022-08-10 19:34 UTC, thomcom approved these changes

2022-08-10 19:44 UTC, trxcllnt commented
@gpucibot merge

2022-08-11 03:41 UTC, harrism approved these changes
The original seems to work on the latest ToT NVCC so the bug may be already fixed. In any case, this workaround is not as offensive so approving.

2022-08-11 03:41 UTC, merged