Introduce ULP Based Floating Point Equality Test to Device Function
rapidsai/cuspatial pull request #773
Opened 2022-11-03 04:54 UTC by isVoid

## Description

This PR adds `float_eq_by_ulp` utility to allow practical near equality for floating point computation in device code.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cuspatial/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2022-11-04 15:26 UTC, thomcom approved these changes
Wow, I'm really impressed.

2022-11-04 17:58 UTC, isVoid commented on cpp/benchmarks/floating_point_equality.cu
> +  cuspatial::rmm_pool_raii rmm_pool;
It make uses of [RAII](https://en.cppreference.com/w/cpp/language/raii) in C++ to automatically allocate/deallocate the memory pool based on the lifetime of this variable. So yes it does something.

2022-11-06 10:21 UTC, harrism requested changes
Very useful!

2022-11-06 10:21 UTC, harrism commented on cpp/include/cuspatial/detail/utility/floating_point.cuh
> +bool CUSPATIAL_HOST_DEVICE float_eq_by_ulp(T const& flhs, T const& frhs)
Minimise nonobvious abbreviations. I think the ulp template parameter is enough to qualify the usage.

```suggestion
bool CUSPATIAL_HOST_DEVICE float_equal(T const& lhs, T const& rhs)
```

2022-11-06 10:21 UTC, harrism commented on cpp/include/cuspatial/detail/utility/floating_point.cuh
> + * @brief ULP (Unit in the last place) based equivalence comparator for floating points.
```suggestion
 * @brief Floating-point equivalence comparator based on ULP (Unit in the last place).
```

2022-11-06 10:21 UTC, harrism commented on cpp/tests/utility_test/test_float_equivalent.cu
> +  return increment(nextafter(f, std::numeric_limits<T>::max()), step - 1);
Does nextafter require `std::`?

2022-11-07 19:42 UTC, isVoid commented
rerun tests

2022-11-07 23:20 UTC, harrism approved these changes

2022-11-07 23:20 UTC, harrism commented
@gpucibot merge

2022-11-07 23:20 UTC, merged