Globally replace "polyline" with "linestring"
rapidsai/cuspatial pull request #788
Opened 2022-11-08 06:20 UTC by harrism

## Description
Replaces all uses of "polyline" (and abbreviations) globally in cuspatial with "linestring" for consistency.  

Fixes #520

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cuspatial/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2022-11-08 18:25 UTC, isVoid approved these changes
Thanks!

2022-11-08 22:50 UTC, thomcom requested changes
Looks good, thanks for taking this on. I just noticed one filename that you missed.

2022-11-08 23:09 UTC, harrism commented on cpp/src/join/quadtree_poly_filtering.cu
>  inline std::unique_ptr<cudf::table> join_quadtree_and_bboxes(cudf::table_view const& quadtree,
Good idea.

2022-11-08 23:33 UTC, harrism commented on cpp/src/join/quadtree_poly_filtering.cu
>  inline std::unique_ptr<cudf::table> join_quadtree_and_bboxes(cudf::table_view const& quadtree,
Done.

2022-11-09 01:19 UTC, harrism commented
@gpucibot merge

2022-11-09 01:19 UTC, merged