Add ZipCode Counting Notebook
rapidsai/cuspatial pull request #919
Opened 2023-02-13 20:13 UTC by isVoid

## Description

This PR adds a notebook that demonstrate the use of quadtree PiP with a custom `QuadTree` structure and joins dataframe. We can use this PR to discuss the possibility of adding the custom structure to the codebase.

This also updates the dependency list to include notebook environment in "all" targeted conda envs.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cuspatial/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2023-02-14 02:40 UTC, isVoid commented
Pending update to Quadtree parameters.

2023-02-15 00:17 UTC, harrism requested changes
Just tidying up the text content.

2023-02-15 00:17 UTC, harrism commented on notebooks/ZipCodes_Stops_PiP_cuSpatial.ipynb
> +    "3. Count the stop signs by zipcodes.\n",
```suggestion
    "Stop signs are an important symbol of city and road development in geographical information systems. This notebook processes all stop sign locations from the dataset, using spatial joins to locate them within the zipcode boundaries located within California. This notebook performs the following steps:\n",
    "1. Filters the zipcode boundaries located in California with spatial join.\n",
    "2. Filters the stop signs located in all the zipcodes with spatial join.\n",
    "3. Counts the stop signs by zipcode.\n",
```

2023-02-15 00:17 UTC, harrism commented on notebooks/ZipCodes_Stops_PiP_cuSpatial.ipynb
> +    "We load the dataset and store them as device dataframe in cuspatial. Note that the second cell below loads the dataset with cuDF, then adopts geopandas to parse the WKT strings into shapely obje
```suggestion
    "We load the datasets and store them as cuSpatial device dataframes. Note that the second cell below loads the dataset with cuDF, then adopts geopandas to parse the WKT (Well-Known Text) strings into shapely objects. This is a slow step performed on CPU and requires data transfer between device and host."
```

2023-02-15 00:17 UTC, harrism commented on notebooks/ZipCodes_Stops_PiP_cuSpatial.ipynb
> +    "# Roundtrip back to geopandas\n",
```suggestion
    "# Transfer back to GPU with cuSpatial\n",
```

2023-02-15 00:17 UTC, harrism commented on notebooks/ZipCodes_Stops_PiP_cuSpatial.ipynb
> +    "The Zipcode Dataset contains boundaries for all zipcodes in the US. The below uses the geometric center for each zipcode and uses cuspatial's quadtree interface to filter zipcodes that locates o
```suggestion
    "The Zipcode Dataset contains boundaries for all zipcodes in the US. The below uses the geometric center for each zipcode and uses cuspatial's quadtree interface to filter zipcodes located only in California."
```

2023-02-15 00:17 UTC, harrism commented on notebooks/ZipCodes_Stops_PiP_cuSpatial.ipynb
> +    "# Build a 2nd quadtree with all stop signs in US\n",
```suggestion
    "# Build a second quadtree with all stop signs in the US\n",
```

2023-02-15 00:17 UTC, harrism commented on notebooks/ZipCodes_Stops_PiP_cuSpatial.ipynb
> +    "The below resorts to [cuDF](https://docs.rapids.ai/api/cudf/stable/index.html) and counts the number of stop signs per zip code. Then merge the geometry information from the zipcode dataset."
"resorts to" has a negative connotation.
```suggestion
    "The below uses [cuDF](https://docs.rapids.ai/api/cudf/stable/index.html) to count the number of stop signs per zip code. Then merge the geometry information from the zipcode dataset."
```

2023-02-15 16:04 UTC, thomcom commented on notebooks/ZipCodes_Stops_PiP_cuSpatial.ipynb
> +    "Dataset used (TODO: discuss if need to self host):\n",
I'm not inclined to self host, but it does have future regression implications to not do so.

2023-02-24 23:53 UTC, isVoid commented on notebooks/ZipCodes_Stops_PiP_cuSpatial.ipynb
> +    "Dataset used (TODO: discuss if need to self host):\n",
Hmm. I think the datasets used for this notebook is from OSM and processed into a csv file. I don't think they can be downloaded as is.

2023-03-06 14:43 UTC, thomcom commented on notebooks/ZipCodes_Stops_PiP_cuSpatial.ipynb
> +    "Dataset used (TODO: discuss if need to self host):\n",
Hey @taureandyernv are we clear to do automatic downloads from self hosted storage for these large datasets and run them in your testing framework?

2023-03-13 14:07 UTC, thomcom requested changes
Do we have a plan for getting the remote datasets yet? @taureandyernv did you see my post above?

2023-03-13 23:51 UTC, isVoid commented
> Do we have a plan for getting the remote datasets yet? @taureandyernv did you see my post above?

Yes, @jarmak-nv has helped me to upload them to s3. But legal is still working through the authorization.

2023-03-23 01:20 UTC, isVoid commented on dependencies.yaml
> +          - pydeck
Added.

2023-03-23 01:44 UTC, isVoid commented
@ajschmidt8 What's `pr / checks / check-generated-files` for and why does it fail?

2023-03-23 17:01 UTC, taureandyernv commented on notebooks/ZipCodes_Stops_PiP_cuSpatial.ipynb
> +    "Dataset used (TODO: discuss if need to self host):\n",
yeah

2023-03-23 20:46 UTC, ajschmidt8 commented
> I will open up a separate PR to add this to `cuspatial` as a pre-commit hook similarly to [cudf](https://github.com/rapidsai/cudf/pull/12819), [cuml](https://github.com/rapidsai/cuml/pull/5246), etc.

PR opened below for reference:

- https://github.com/rapidsai/cuspatial/pull/1008

2023-03-23 21:51 UTC, thomcom approved these changes
Looking good.

2023-03-27 15:39 UTC, merged